server:
  port: 10055
spring:
  rabbitmq:
    host: 39.105.189.141
    port: 5672
    username: guest
    password: guest
application:
  name: mqListener
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


